// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace April20.Migrations
{
    [DbContext(typeof(VideotekaContext))]
    [Migration("20220119214835_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.DVD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<int?>("KluboviID")
                        .HasColumnType("int");

                    b.Property<int?>("PoliceID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KluboviID");

                    b.HasIndex("PoliceID");

                    b.ToTable("DVDS");
                });

            modelBuilder.Entity("Models.Police", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Velicina")
                        .HasColumnType("int");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Police");
                });

            modelBuilder.Entity("Models.VideoKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("VideoKlubovi");
                });

            modelBuilder.Entity("Models.DVD", b =>
                {
                    b.HasOne("Models.VideoKlub", "Klubovi")
                        .WithMany("KlubDVD")
                        .HasForeignKey("KluboviID");

                    b.HasOne("Models.Police", "Police")
                        .WithMany("PoliceDVD")
                        .HasForeignKey("PoliceID");

                    b.Navigation("Klubovi");

                    b.Navigation("Police");
                });

            modelBuilder.Entity("Models.Police", b =>
                {
                    b.Navigation("PoliceDVD");
                });

            modelBuilder.Entity("Models.VideoKlub", b =>
                {
                    b.Navigation("KlubDVD");
                });
#pragma warning restore 612, 618
        }
    }
}
